name: Build-and-Test-Program
on:
  push:
    branches:
      - main

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Install g++
        run: |
          sudo apt install g++
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print working directory
        run: |
          pwd
      - name: Show directory contents
        run: |
          ls
      - name: Build program
        run: |
          sudo g++ src/main.cpp -o test.out
      - name: Run program
        run: |
          sudo ./test.out
